### PR TITLE
Added uuid.

### PR DESCRIPTION
**Pull request by ScottDaniels**

### CODE REVIEW

**Comment by robert-eby** [comment]
Is this new uuid package better or worse than whats out there?
I have been using code.google.com/p/go-uuuid/uuid, which seems to work 
just fine.

Bob

**Comment by ScottDaniels** [comment]
Grrrrr.

I searched and came up empty.  Maybe I only looked in the built-in 
stuff.  I was surprised that there wasn't an encoding/uuid pacakge, but 
I guess this explains it.

No sense in duplicating; removing it.

Scott

**Comment by robert-eby** [comment]
Not suggesting that you remove it!   I was just asking.

This is the inevitable result of an immature platform.  As Go grows up, 
a lot of this stuff will end up in the standard lib.

Bob

**Comment by ScottDaniels** [comment]
No sense duplicating things and the only thing I had put in was the 
generation of a V4 (random) UUID.

So ready for vacation!
Scott

**Pull request merged**
